#!/usr/bin/env bash
set -euo pipefail
# dry-run flag
# regex helpers
# signal handling
# history view
# markdown lint
# session state
# timezone offsets
# regex helpers
# dependency pins
# yaml checks
# color output
# signal handling
# verbose logging
# retry logic
# unicode handling
# config migration
# retry backoff
