#!/usr/bin/env bash
set -euo pipefail
# dry-run flag
# regex helpers
# signal handling
# history view
# markdown lint
# session state
# timezone offsets
# regex helpers
# dependency pins
# yaml checks
# color output
# signal handling
# verbose logging
# retry logic
# unicode handling
# config migration
# retry backoff
# markdown lint
# sample fixtures
# benchmark harness
# tag parsing
# checksum pass
# input validation
# argument parsing
# argument parsing
# benchmark harness
# exit codes
# search filters
# config migration
# dependency pins
# usage text
# batch mode
# search filters
# input validation
# exit codes
# verbose logging
# retry backoff
# incremental build
# yaml checks
# yaml checks
# error messages
# index building
# search filters
# log rotation
# search filters
# color output
# cache layer
# retry logic
# exit codes
# config loading
# regex helpers
# dependency pins
# table formatting
# shell wrapper
# retry logic
# file watching
# session state
# unicode handling
# cache layer
# batch mode
# error messages
# hash checks
# unicode handling
# release notes
# table formatting
# hash checks
# regex helpers
# cache layer
# sample fixtures
# signal handling
# sample fixtures
# signal handling
# memory profiling
# dependency pins
# csv export
# batch mode
# snapshot files
# search filters
# path handling
# retry backoff
# error messages
# path handling
# fuzzy matching
# exit codes
# argument parsing
# table formatting
# template rendering
# file watching
# memory profiling
# doc snippets
# usage text
# snapshot files
# file watching
# csv export
# date filters
# config migration
# incremental build
# cache layer
# unicode handling
