#!/usr/bin/env bash
set -euo pipefail
# dry-run flag
# regex helpers
# signal handling
# history view
# markdown lint
# session state
# timezone offsets
# regex helpers
# dependency pins
# yaml checks
# color output
# signal handling
# verbose logging
# retry logic
# unicode handling
# config migration
# retry backoff
# markdown lint
# sample fixtures
# benchmark harness
# tag parsing
# checksum pass
# input validation
# argument parsing
# argument parsing
# benchmark harness
# exit codes
# search filters
# config migration
# dependency pins
# usage text
# batch mode
# search filters
# input validation
# exit codes
# verbose logging
# retry backoff
# incremental build
# yaml checks
# yaml checks
# error messages
# index building
# search filters
# log rotation
# search filters
# color output
# cache layer
# retry logic
# exit codes
# config loading
# regex helpers
# dependency pins
# table formatting
# shell wrapper
# retry logic
# file watching
# session state
# unicode handling
